import turtle
#рисунки
t = turtle.Pen()
def Square(x,y,speed,size,color,angel):
    t.pendown ()
    t.color(color)
    t.penup()
    t.setx(x)
    t.sety(y)
    t.speed(speed)
    t.begin_fill()
    t.pendown()
    t.forward(size)
    t.right(angel)
    t.forward(size)
    t.right(angel)
    t.forward(size)
    t.right(angel)
    t.forward(size)
    t.end_fill()

def Triangle(x,y,a,h,color,angel):
    t.penup()
    t.setx(x)
    t.sety(y)
    t.color(color)
    t.begin_fill()
    t.pendown()
    t.rt(angel)
    t.forward(a)
    t.lt(angel)
    t.forward(h)
    t.goto(x,y)
    t.end_fill()

def Triangle1(x,y,a,h,color,angel):
    t.penup()
    t.setx(x)
    t.sety(y)
    t.color(color)
    t.begin_fill()
    t.pendown()
    t.lt(angel)
    t.forward(a)
    t.rt(angel)
    t.forward(h)
    t.goto(x,y)
    t.end_fill()

def Rectangule(x,y,a,b,color,angel):
    t.pendown ()
    t.color (color)
    t.penup ()
    t.setx ( x )
    t.sety ( y )
    t.begin_fill ()
    t.pendown ( )
    t.lt(angel)
    t.forward (a)
    t.lt(angel)
    t.forward (b)
    t.lt (angel)
    t.forward (a)
    t.goto(x, y)
    t.end_fill ()

def Circ(x,y,r,color):
    t.pendown ()
    t.color (color)
    t.penup ()
    t.setx ( x )
    t.sety ( y )
    t.begin_fill ()
    t.pendown ( )
    t.circle(r)
    t.end_fill ()

Square(-200, 0, 10, 200, "orange", 90)
Triangle(-250,0,150,90,"blue",90)
Triangle1(50,0,150,90,"blue",90)
Square(-180, -70, 10, 60, "yellow", 90)
Square(-20, -70, 10, 60, "yellow", 90)
Rectangule(-70,50,30,70,"red",90)
Rectangule(-400,-200,10,800,"green",90)
Rectangule(250,-125,175,50,"silver",90)
Rectangule(300,-175,70,40,"lime",90)
Rectangule(300,-175,60,40,"lime",90)
Triangle(330,-135,42,30,"lime",45)
Circ(300,-160,20,"black")
Circ(200,-160,20,"black")
Circ(125,-160,20,"black")
Rectangule(-150,-110,90,40,"silver",90)

turtle.mainloop()
